In [1]:
#라이브러리 불러오기
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format='retina'

np.random.seed(63)

In [2]:
# DataSet 불러오기 레드와인 데이터
red = pd.read_csv('winequality-red.csv', sep=';') # comma 대신 semi colon으로 데이터가 구분되어있다.
white = pd.read_csv('winequality-white.csv', sep=';')

In [3]:
red

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [4]:
red['kind']= 1
red

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,kind
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,1
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,1
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,1
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,1

In [5]:
white['kind']=0
white

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,kind
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6,0
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6,0
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6,0
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,0
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,0
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,0
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,0
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,0
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,0

In [18]:
target = 'quality'
target_class = 'kind'
features = red.columns.drop([target, target_class])

In [19]:
train_all, val_all = train_test_split(all_wine, test_size=0.1, random_state=63)

train_all, test_all = train_test_split(train_all, test_size=0.25, random_state=63)

In [20]:
X_train_all = train_all[features]
y_train_all = train_all[target]
y_train_k_all = train_all[target_class]

X_val_all = val_all[features]
y_val_all = val_all[target]
y_val_k_all = val_all[target_class]

X_test_all = test_all[features]
y_test_all = test_all[target]
y_test_k_all = test_all[target_class]

X_train_all.shape, y_train_all.shape, y_train_k_all.shape, X_val_all.shape, y_val_all.shape, y_val_k_all.shape, X_test_all.shape, y_test_all.shape, y_test_all.shape

((3897, 11),
 (3897,),
 (3897,),
 (1300, 11),
 (1300,),
 (1300,),
 (1300, 11),
 (1300,),
 (1300,))

#### Baseline (If all Guess as Red, 32% change of being right.)

In [6]:
1599/4898

0.32645977950183747

# Classification - Red Wine or White Wine

In [17]:
all_wine = pd.concat([red, white])
all_wine.reset_index(drop=True)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,kind
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,1
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,1
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,1
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,0
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,0
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,0
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,0
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,0

## Random Forest Classifier - Red or White

In [21]:
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

#파이프라인
pipe = make_pipeline(
    RandomForestClassifier(n_jobs=-1,
                          oob_score=True,
                          random_state=63,
                          max_depth = 50,
                          )
)

#훈련
pipe.fit(X_train_all, y_train_k_all)

#예측
y_pred_all = pipe.predict(X_val_all)

#정확도
print('훈련 정확도 : ',pipe.score(X_train_all, y_train_k_all))
print('검증 정확도 (model.score): ',pipe.score(X_val_all, y_val_k_all))
print('Test 정확도 (model.score): ',pipe.score(X_test_all, y_test_k_all))
print('Out Of Bag 을 사용한 검증 정확도 : ',pipe.named_steps['randomforestclassifier'].oob_score_)
print('훈련-검증 차이', pipe.score(X_train_all, y_train_k_all) - pipe.score(X_val_all, y_val_k_all))
print('---')
print('Classification Report For Train \n', classification_report(y_test_k_all, y_pred_all)) #훈련

훈련 정확도 :  0.9997433923530922
검증 정확도 (model.score):  0.9907692307692307
Test 정확도 (model.score):  0.9953846153846154
Out Of Bag 을 사용한 검증 정확도 :  0.9953810623556582
훈련-검증 차이 0.00897416158386144
---
Classification Report For Train
               precision    recall  f1-score   support

           0       0.78      0.76      0.77      1005
           1       0.23      0.25      0.24       295

    accuracy                           0.64      1300
   macro avg       0.50      0.50      0.50      1300
weighted avg       0.65      0.64      0.65      1300

In [22]:
import tensorflow as tf
from tensorflow.keras.layers import Flatten, Dense, Dropout
from tensorflow.keras.models import Sequential

tf.random.set_seed(63)

In [23]:
model_classification = Sequential([
    Dense(64, activation='relu', input_dim=11),
    Dense(128, activation='relu'),
    Dense(256, activation='relu'),
    Dropout(0.1),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid'),
])

model_classification.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

In [24]:
model_classification.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 64)                768
_________________________________________________________________
dense_1 (Dense)              (None, 128)               8320
_________________________________________________________________
dense_2 (Dense)              (None, 256)               33024
_________________________________________________________________
dropout (Dropout)            (None, 256)               0
_________________________________________________________________
dense_3 (Dense)              (None, 128)               32896
_________________________________________________________________
dense_4 (Dense)              (None, 64)                8256
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 65
=================================================================
Total params: 83,329
Trainable params: 83,329
Non-trainable params: 0
_________________________________________________________________

In [25]:
early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=10, verbose=1)

hist = model_classification.fit(X_train_all, y_train_k_all,
                                epochs=75,
                               verbose=1,
                               validation_data=(X_val_all, y_val_k_all),
                               callbacks=[early_stop])

Epoch 1/75
122/122 [==============================] - 1s 2ms/step - loss: 0.4845 - acc: 0.8524 - val_loss: 0.2111 - val_acc: 0.9308
Epoch 2/75
122/122 [==============================] - 0s 909us/step - loss: 0.2261 - acc: 0.9247 - val_loss: 0.1915 - val_acc: 0.9308
Epoch 3/75
122/122 [==============================] - 0s 920us/step - loss: 0.1925 - acc: 0.9355 - val_loss: 0.2169 - val_acc: 0.9192
Epoch 4/75
122/122 [==============================] - 0s 926us/step - loss: 0.1660 - acc: 0.9456 - val_loss: 0.1648 - val_acc: 0.9408
Epoch 5/75
122/122 [==============================] - 0s 900us/step - loss: 0.1745 - acc: 0.9423 - val_loss: 0.1556 - val_acc: 0.9438
Epoch 6/75
122/122 [==============================] - 0s 896us/step - loss: 0.1509 - acc: 0.9439 - val_loss: 0.1776 - val_acc: 0.9446
Epoch 7/75
122/122 [==============================] - 0s 917us/step - loss: 0.1533 - acc: 0.9464 - val_loss: 0.1997 - val_acc: 0.9308
Epoch 8/75
122/122 [==============================] - 0s 971us/step - loss: 0.1550 - acc: 0.9464 - val_loss: 0.1434 - val_acc: 0.9477
Epoch 9/75
122/122 [==============================] - 0s 952us/step - loss: 0.1465 - acc: 0.9523 - val_loss: 0.1129 - val_acc: 0.9623
Epoch 10/75
122/122 [==============================] - 0s 944us/step - loss: 0.1081 - acc: 0.9655 - val_loss: 0.1102 - val_acc: 0.9600
Epoch 11/75
122/122 [==============================] - 0s 965us/step - loss: 0.0968 - acc: 0.9685 - val_loss: 0.1092 - val_acc: 0.9731
Epoch 12/75
122/122 [==============================] - 0s 953us/step - loss: 0.1030 - acc: 0.9676 - val_loss: 0.1414 - val_acc: 0.9531
Epoch 13/75
122/122 [==============================] - 0s 943us/step - loss: 0.1141 - acc: 0.9625 - val_loss: 0.1061 - val_acc: 0.9608
Epoch 14/75
122/122 [==============================] - 0s 954us/step - loss: 0.1084 - acc: 0.9679 - val_loss: 0.0927 - val_acc: 0.9731
Epoch 15/75
122/122 [==============================] - 0s 904us/step - loss: 0.0861 - acc: 0.9778 - val_loss: 0.0986 - val_acc: 0.9631
Epoch 16/75
122/122 [==============================] - 0s 893us/step - loss: 0.0783 - acc: 0.9770 - val_loss: 0.0839 - val_acc: 0.9785
Epoch 17/75
122/122 [==============================] - 0s 907us/step - loss: 0.0806 - acc: 0.9738 - val_loss: 0.1056 - val_acc: 0.9646
Epoch 18/75
122/122 [==============================] - 0s 947us/step - loss: 0.0816 - acc: 0.9730 - val_loss: 0.0947 - val_acc: 0.9754
Epoch 19/75
122/122 [==============================] - 0s 965us/step - loss: 0.0862 - acc: 0.9709 - val_loss: 0.0849 - val_acc: 0.9762
Epoch 20/75
122/122 [==============================] - 0s 908us/step - loss: 0.0936 - acc: 0.9695 - val_loss: 0.0813 - val_acc: 0.9762
Epoch 21/75
122/122 [==============================] - 0s 967us/step - loss: 0.0666 - acc: 0.9802 - val_loss: 0.0795 - val_acc: 0.9754
Epoch 22/75
122/122 [==============================] - 0s 957us/step - loss: 0.0595 - acc: 0.9831 - val_loss: 0.0787 - val_acc: 0.9769
Epoch 23/75
122/122 [==============================] - 0s 897us/step - loss: 0.0936 - acc: 0.9717 - val_loss: 0.0736 - val_acc: 0.9754
Epoch 24/75
122/122 [==============================] - 0s 898us/step - loss: 0.0694 - acc: 0.9793 - val_loss: 0.0871 - val_acc: 0.9746
Epoch 25/75
122/122 [==============================] - 0s 881us/step - loss: 0.0728 - acc: 0.9758 - val_loss: 0.0867 - val_acc: 0.9777
Epoch 26/75
122/122 [==============================] - 0s 901us/step - loss: 0.0573 - acc: 0.9792 - val_loss: 0.0882 - val_acc: 0.9754
Epoch 27/75
122/122 [==============================] - 0s 895us/step - loss: 0.0675 - acc: 0.9816 - val_loss: 0.0697 - val_acc: 0.9785
Epoch 28/75
122/122 [==============================] - 0s 883us/step - loss: 0.0763 - acc: 0.9754 - val_loss: 0.0864 - val_acc: 0.9754
Epoch 29/75
122/122 [==============================] - 0s 897us/step - loss: 0.0749 - acc: 0.9782 - val_loss: 0.0688 - val_acc: 0.9800
Epoch 30/75
122/122 [==============================] - 0s 889us/step - loss: 0.0661 - acc: 0.9827 - val_loss: 0.0726 - val_acc: 0.9800
Epoch 31/75
122/122 [==============================] - 0s 929us/step - loss: 0.0570 - acc: 0.9841 - val_loss: 0.0703 - val_acc: 0.9777
Epoch 32/75
122/122 [==============================] - 0s 942us/step - loss: 0.0600 - acc: 0.9820 - val_loss: 0.0676 - val_acc: 0.9769
Epoch 33/75
122/122 [==============================] - 0s 922us/step - loss: 0.0676 - acc: 0.9776 - val_loss: 0.0752 - val_acc: 0.9815
Epoch 34/75
122/122 [==============================] - 0s 885us/step - loss: 0.0618 - acc: 0.9824 - val_loss: 0.0723 - val_acc: 0.9792
Epoch 35/75
122/122 [==============================] - 0s 890us/step - loss: 0.0380 - acc: 0.9873 - val_loss: 0.0836 - val_acc: 0.9769
Epoch 36/75
122/122 [==============================] - 0s 892us/step - loss: 0.0720 - acc: 0.9769 - val_loss: 0.0679 - val_acc: 0.9800
Epoch 37/75
122/122 [==============================] - 0s 885us/step - loss: 0.0604 - acc: 0.9809 - val_loss: 0.0668 - val_acc: 0.9800
Epoch 38/75
122/122 [==============================] - 0s 944us/step - loss: 0.0505 - acc: 0.9835 - val_loss: 0.0643 - val_acc: 0.9815
Epoch 39/75
122/122 [==============================] - 0s 951us/step - loss: 0.0649 - acc: 0.9826 - val_loss: 0.0651 - val_acc: 0.9823
Epoch 40/75
122/122 [==============================] - 0s 940us/step - loss: 0.0593 - acc: 0.9853 - val_loss: 0.1244 - val_acc: 0.9608
Epoch 41/75
122/122 [==============================] - 0s 987us/step - loss: 0.0586 - acc: 0.9839 - val_loss: 0.0687 - val_acc: 0.9792
Epoch 42/75
122/122 [==============================] - 0s 911us/step - loss: 0.0494 - acc: 0.9857 - val_loss: 0.0687 - val_acc: 0.9808
Epoch 43/75
122/122 [==============================] - 0s 970us/step - loss: 0.0568 - acc: 0.9845 - val_loss: 0.0613 - val_acc: 0.9831
Epoch 44/75
122/122 [==============================] - 0s 922us/step - loss: 0.0582 - acc: 0.9820 - val_loss: 0.0601 - val_acc: 0.9831
Epoch 45/75
122/122 [==============================] - 0s 968us/step - loss: 0.0526 - acc: 0.9865 - val_loss: 0.0645 - val_acc: 0.9815
Epoch 46/75
122/122 [==============================] - 0s 949us/step - loss: 0.0512 - acc: 0.9833 - val_loss: 0.0763 - val_acc: 0.9800
Epoch 47/75
122/122 [==============================] - 0s 914us/step - loss: 0.0592 - acc: 0.9837 - val_loss: 0.0750 - val_acc: 0.9800
Epoch 48/75
122/122 [==============================] - 0s 916us/step - loss: 0.0497 - acc: 0.9840 - val_loss: 0.0648 - val_acc: 0.9831
Epoch 49/75
122/122 [==============================] - 0s 911us/step - loss: 0.0513 - acc: 0.9844 - val_loss: 0.0896 - val_acc: 0.9754
Epoch 50/75
122/122 [==============================] - 0s 915us/step - loss: 0.0706 - acc: 0.9784 - val_loss: 0.0771 - val_acc: 0.9815
Epoch 51/75
122/122 [==============================] - 0s 922us/step - loss: 0.0417 - acc: 0.9851 - val_loss: 0.0617 - val_acc: 0.9831
Epoch 52/75
122/122 [==============================] - 0s 877us/step - loss: 0.0420 - acc: 0.9866 - val_loss: 0.0638 - val_acc: 0.9838
Epoch 53/75
122/122 [==============================] - 0s 903us/step - loss: 0.0505 - acc: 0.9849 - val_loss: 0.0680 - val_acc: 0.9785
Epoch 54/75
122/122 [==============================] - 0s 907us/step - loss: 0.0561 - acc: 0.9801 - val_loss: 0.0770 - val_acc: 0.9815
Epoch 00054: early stopping

Validation Loss를 기준으로 가장 성능이 좋았던 모델은

Epoch 44 : loss: 0.0582 - acc: 0.9820 - val_loss: 0.0601 - val_acc: 0.9831
훈련 정확도: 0.982, 검증 정확도:0.9831